#!/usr/bin/env bash
# This script pings an IP address passed as an argument

if [[ $# -eq 0 ]]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi

ip_address=$1

echo "PING $ip_address"
ping_result=$(ping -c 5 $ip_address)
echo "$ping_result"

rtt_stats=$(echo "$ping_result" | grep -oP 'rtt min/avg/max/mdev = \K[^ ]+')
echo ""
echo "--- $ip_address ping ---"
echo "$rtt_stats ms"

